spring:
  application:
    name: Spring-Actuator-Example
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
        exclude:
        - "beans"   
#  endpoint:
#    shutdown:
#      enabled: true